# Copyright (c) 2022 Bradley J. Tannor. All rights reserved. Released under the
# MIT License. Refer LICENSE.txt.

class DataType
  VERSION: String

  def self.types: () -> Array

  def self.instance?: (object: BasicObject) -> Boolean

  def self.type?: (type: BasicObject) -> Boolean

  def self.types_element?: (type: BasicObject) -> Boolean
 
  def self.type_child?: (type: BasicObject) -> Boolean

  TYPES: Array
end
